name: build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:

      - name: setup-podman
        uses: TerrorJack/setup-podman@master

      - name: build-image
        run: |
          pushd "$(mktemp -d)"
          curl -f -L --retry 5 https://github.com/tweag/rust-alpine-mimalloc/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
          podman build \
            --network host \
            --pull \
            --squash-all \
            --tag rust:alpine-mimalloc \
            .
          popd

      - name: checkout
        uses: actions/checkout@v4

      - name: build-node
        run: |
          podman run \
            --init \
            --network host \
            --rm \
            --tmpfs /tmp:exec \
            --volume $PWD:/workspace \
            --workdir /workspace \
            rust:alpine-mimalloc \
            /workspace/build.sh

      - name: test-node
        run: |
          tar xJf node-v*-linux-x64-static.tar.xz
          export PATH=$PWD/node-v*-linux-x64-static/bin:$PATH
          npm install @bjorn3/browser_wasi_shim

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-linux-x64-static
          path: node-v*-linux-x64-static.tar.xz
